### ISSUE TITLE
Event type for conferences (not pre or post show)

### ISSUE THREAD

**Issue by troughc** [culturecreates/artsdata-data-model#48]
We have seen conferences (Isabelle commented on this one: https://console.footlight.io/events/adr:spec-qc-ca_la-richesse-des-arts-autochtones

Which event type captures something like this? 
cc @tammy-culture @saumier

**Comment by saumier** [comment]
See #50 to have a discussion about this.

**Comment by saumier** [comment]
[http://kg.artsdata.ca/resource/Conference](http://kg.artsdata.ca/resource/Conference) has been created in the Artsdata Event Type controlled vocabulary.
