### ISSUE TITLE
Event type for Story teller

### ISSUE THREAD

**Issue by troughc** [culturecreates/artsdata-data-model#49]
Fred Pellerin is a storyteller - Isabelle from SPEC wanted that as a category for this event: https://console.footlight.io/events/adr:spec-qc-ca_fred-pellerin

What type would capture this kind of performance? (no spoken word in my opinion).

cc @tammy-culture @saumier

**Comment by tammy-culture** [comment]
No need to add CONTE as its own event category after the discussion with Frederic and LDF.  In the future, it will be the responsibility of the Artsdata Partner's Group to update event types and organization types.

**Comment by saumier** [comment]
@tammy-culture After discussing with Fred, Tammy decided to not add Story Teller.
