### ISSUE TITLE
Typo in event type ChansonFrancophone

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-data-model#76]
Christian Roy pointed out that the Artsdata event type for Chanson francophone has a type in the label in french. It should be lower case 'f' for francophone instead of upper case 'F' as it currently is in http://kg.artsdata.ca/resource/ArtsdataEventTypes v3.3.2

http://kg.artsdata.ca/resource/ChansonFrancophone

**Comment by saumier** [comment]
@tammy-culture Please fix this typo and let me know when you are done so I can re-publish the controlled vocabulary for Artsdata Event Types.

**Comment by tammy-culture** [comment]
I did it here https://docs.google.com/spreadsheets/d/1ud_kVTE8C97ZMoe1uYGQ6rW_dodKqsbqiCutLLHO9jo/edit#gid=0. 

Is that right?


Tammy Lee | PDG - cofondatrice - CEO - Co-founder | La culture crée - Culture Creates | c. (514) 465-1385 | culturecreates.com <http://www.culturecreates.com/> 
Nous reconnaissons que notre entreprise est située sur le territoire Kanien’kehá:ka non cédé. / We acknowledge that our business is located on unceded Kanien’kehá:ka territory.

**Comment by saumier** [comment]
> I did it here https://docs.google.com/spreadsheets/d/1ud_kVTE8C97ZMoe1uYGQ6rW_dodKqsbqiCutLLHO9jo/edit#gid=0. Is that right?

Yes. Thx. I will publish the update as a minor patch to version 3.  That means the last digit will change to become v3.3.3
